SELECT C1.CNAME FROM CUSTOMER C1,DEPOSIT D1,
BRANCH B1 WHERE  C1.CNAME IN((SELECT BR1.CNAME FROM BORROW BR1) INTERSECT (SELECT D2.CNAME FROM DEPOSIT D2))
AND  D1.CNAME = C1.CNAME  AND  D1.BNAME = B1.BNAME
AND  B1.CITY IN(SELECT B2.CITY FROM DEPOSIT D3, BRANCH B2 WHERE D3.CNAME = 'ANIL' AND D3.BNAME = B2.BNAME);
