SELECT D1.CNAME FROM DEPOSIT D1 WHERE D1.CNAME IN
((SELECT D2.CNAME FROM DEPOSIT D2 ,
CUSTOMER C1 WHERE C1.CITY = 'NAGPUR' AND D2.CNAME = C1.CNAME)
INTERSECT (SELECT D3.CNAME FROM DEPOSIT D3,  BRANCH B1
WHERE B1.CITY = 'DELHI' AND D3.BNAME = B1.BNAME));
