UPDATE DEPOSIT SET AMOUNT = AMOUNT + 10 WHERE CNAME IN
(SELECT D1.CNAME FROM DEPOSIT D1,CUSTOMER C1 WHERE
C1.CNAME = D1.CNAME GROUP BY D1.CNAME HAVING
AVG(D1.AMOUNT) >= ALL (SELECT D2.AMOUNT
FROM DEPOSIT D2, CUSTOMER C2,CUSTOMER C1
WHERE D2.CNAME = C2.CNAME AND C2.CITY = C1.CITY));
