SELECT C1.CNAME FROM CUSTOMER C1,BRANCH B1,DEPOSIT D3
WHERE C1.CITY = ‘MUMBAI’ AND
C1.CNAME IN ((SELECT D1.CNAME FROM DEPOSIT D1)
UNION
(SELECT BR1.CNAME FROM BORROW BR1))
AND
B1.CITY IN
(SELECT B2.CITY FROM DEPOSIT D2, BRANCH B2 WHERE D2.CNAME = ‘SANDIP’
AND D2.BNAME = B2.BNAME
AND
C1.CNAME = D3.CNAME AND D3.BNAME = B1.BNAME);
