CREATE TABLE DEPOSIT (ACTNO VARCHAR2(5), CNAME VARCHAR2 (18), 			BNAME VARCHAR2(18), AMOUNT NUMBER(8,2), ADATE DATE);
CREATE TABLE BRANCH(BNAME VARCHAR2(18), CITY VARCHAR2(18));
CREATE TABLE CUSTOMER(CNAME VARCHAR2(19), CITY VARCHAR2 (18));
CREATE TABLE BORROW (LOANNO VARCHAR2(5), CNAME VARCHAR2(18), BNAME VARCHAR2(18), 	AMOUNT NUMBER(8,2));
