SELECT D1.CNAME  FROM DEPOSIT D1,  CUSTOMER C1,  BRANCH B1
WHERE D1.CNAME = C1.CNAME  AND D1.BNAME = B1.BNAME AND B1.CITY
IN (SELECT B2.CITY FROM BRANCH B2,  DEPOSIT D2  WHERE D2.CNAME = 'SUNIL' AND 		D2.BNAME = B2.BNAME  AND C1.CITY IN(SELECT C2.CITY FROM CUSTOMER C2 WHERE 		C2.CNAME = 'ANIL'));
