SELECT C1.CNAME FROM CUSTOMER C1 WHERE C1.CNAME IN
((SELECT D1.CNAME FROM DEPOSIT D1)
INTERSECT
(SELECT BR1.CNAME FROM BORROW BR1))
AND
C1.CITY IN
(SELECT C2.CITY FROM CUSTOMER C2 WHERE C2.CNAME = ‘ANIL’);
