INSERT INTO ENQUIRY
(ENQUIRYNO,FNAME,SNAME,COURSECODE,PLOTNO,STREET,CITY,ENQUIRYDATE,REFCODE,EN_ST) 	VALUES (110001,'ANIL','SHARMA',10,'23D','RAMNAGAR','NAGPUR','01-JUL-		00',1001,'Y');  

INSERT INTO ENQUIRY
(ENQUIRYNO,FNAME,SNAME,COURSECODE,PLOTNO,STREET,CITY,ENQUIRYDATE,REF
CODE,EN_ST) VALUES (110002,'SACHIN','NIMJE',20,'20','GANDHI NAGAR','NAGPUR','01-		SEP-00',1002,'Y');
