update BATCH d
set EXPECTEDINCOME = (select sum(a.AMOUNT) 
from INSTALLMENT a,ENROLLMENT b,BATCH c
where a.ROLLNO = b.ROLLNO
and b.BATCHCODE = c.BATCHCODE
and b.BATCHCODE = d.BATCHCODE)
where d.BATCHCODE in
(SELECT BATCHCODE from ENROLLMENT,INSTALLMENT
WHERE ENROLLMENT.ROLLNO = INSTALLMENT.ROLLNO
AND ENROLLMENT.BATCHCODE = d.BATCHCODE);
