SELECT ENROLLMENT.ROLLNO,FNAME, SNAME, ENROLLMENT. BATCHCODE, 		FEESPAID.AMOUNT
FROM ENQUIRY,ENROLLMENT,FEESPAID
WHERE ENQUIRY.ENQUIRYNO = ENROLLMENT.ENQUIRYNO
AND ENROLLMENT.ROLLNO = FEESPAID.ROLLNO
AND ENROLLMENT.BATCHCODE = 10001;
