SELECT (BATCH.COURSEFEES – F1.TOTAL)
FROM (SELECT ROLLNO ROLLNO1, SUM(AMOUNT) TOTAL
FROM FEESPAID
GROUP BY (ROLLNO)) F1, BATCH, ENROLLMENT
WHERE F1.ROLLNO1 = ENROLLMENT.ROLLNO
AND ENROLLMENT.BATCHCODE = BATCH.BATCHCODE
AND F1.ROLLNO1 = 10001100;
