SELECT E1.FNAME||’ ‘||E1.SNAME NAME
FROM ENQUIRY E1, ENQUIRY E2, ENROLLMENT EN1, ENROLLMENT EN2 WHERE E2.FNAME =’ANIL’ 
AND EN1.ENQUIRYNO = E2.ENQUIRYNO
AND EN1.BATCHCODE = EN2.BATCHCODE
AND EN2.ENQUIRYNO = E1.ENQUIRYNO;
