SELECT C.COURSENAME
FROM COURSE C
WHERE C.COURSECODE
IN(SELECT B.COURSECODE
FROM BATCH B
GROUP BY B.COURSECODE
HAVING (SUM(B.EXPECTEDINCOME) – SUM(B.NETINCOME)) >= ALL
(SELECT (SUM(B1.EXPECTEDINCOME) – SUM(B1.NETINCOME)) FROM BATCH  B1
GROUP BY (B1.COURSECODE)));
