SELECT ENROLLMENT.ROLLNO, ENQUIRY.FNAME ||’’|| ENQUIRY.SNAME
FROM ENQUIRY,ENROLLMENT,FEESPAID
WHERE ENQUIRY.ENQUIRYNO = ENROLLMENT.ENQUIRYNO
AND ENROLLMENT.ROLLNO = FEESPAID.ROLLNO
AND FEESPAID.AMOUNT > 2000;
