SELECT ENROLLMENT.ROLLNO, ENQUIRY.FNAME, ENQUIRY. SNAME,
INSTALLMENT.INSTALLMENTDATE, INSTALLMENT.AMOUNT
FROM ENQUIRY, ENROLLMENT, INSTALLMENT
WHERE ENQUIRY.ENQUIRYNO = ENROLLMENT.ENQUIRYNO
AND ENROLLMENT.ROLLNO = INSTALLMENT.ROLLNO
AND ENROLLMENT.BATCHCODE = 10001;
