SELECT FNAME
FROM ENQUIRY E1,ENROLLMENT EN1,BATCH B1
WHERE E1.ENQUIRYNO = EN1.ENQUIRYNO
AND EN1.BATCHCODE = B1.BATCHCODE
AND EXISTS(SELECT * FROM BATCH B2
WHERE STARTINGDATE < ’23-JAN-99'
AND B2.BATCHCODE = B1.BATCHCODE);
