SELECT A.ENROLLMENTDATE, TO_DATE(SYSDATE) – A.ENROLLMENTDATE, COUNT(A.ROLLNO) 
FROM ENROLLMENT A
WHERE TO_DATE(SYSDATE) – A.ENROLLMENTDATE
BETWEEN 1 AND 15
AND BATCHCODE = 1001
GROUP BY A.ENROLLMENTDATE, TO_DATE(SYSDATE) – A.ENROLLMENTDATE
ORDER BY 1;
