UPDATE COURSE C1
SET C1.LASTNO = (SELECT COUNT(*) 
FROM BATCH B1
WHERE B1.COURSECODE = C1.COURSECODE)
WHERE C1.COURSECODE IN
(SELECT B2.COURSECODE FROM BATCH B2
WHERE B2.COURSECODE = C1.COURSECODE); 
