SELECT FNAME
FROM ENQUIRY E1
WHERE
NOT EXISTS((SELECT EN2.BATCHCODE
FROM ENQUIRY E2,ENROLLMENT EN2
WHERE E2.FNAME = ’ANIL’
AND E2.ENQUIRYNO = EN2.ENQUIRYNO)
MINUS
(SELECT EN3.BATCHCODE
FROM ENQUIRY E3,ENROLLMENT EN3
WHERE E3.ENQUIRYNO = EN3.ENQUIRYNO
AND E3.FNAME = E1.FNAME));
