SELECT COURSE.COURSENAME, BATCH.BATCHCODE, BATCH. STARTINGDATE, 
BATCH.DURATION, BATCH.COURSEFEES, BATCH. NETINCOME, BATCH.EXPECTEDINCOME, 		
BATCH.LASTNO FROM COURSE, BATCH WHERE COURSE.COURSECODE = BATCH.COURSECODE;