SELECT E1.FNAME||’ ‘||E1.SNAME FROM ENQUIRY E1, ENQUIRY E2, ENROLLMENT 	EN1,ENROLLMENT EN2,BATCH B1,BATCH B2
WHERE E2.FNAME = ’ANIL’
AND   E2.ENQUIRYNO = EN1.ENQUIRYNO
AND   EN1.BATCHCODE = B1.BATCHCODE
AND   B1.COURSECODE = B2.COURSECODE
AND   B2.BATCHCODE = EN2.BATCHCODE
AND   EN2.ENQUIRYNO = E1.ENQUIRYNO;
