SELECT EN1.ROLLNO,E1.FNAME, E1.SNAME
FROM ENROLLMENT EN1,ENQUIRY E1,INSTALLMENT I1
WHERE EN1.ENQUIRYNO = E1.ENQUIRYNO
AND EN1.ROLLNO = I1.ROLLNO
AND NOT EXISTS (SELECT * FROM FEESPAID F1
WHERE I1.ROLLNO = F1.ROLLNO
AND I1.AMOUNT = F1.AMOUNT
AND I1.INSTALLMENTDATE = F1. FEESPAIDDATE)
/
