SELECT TRUNC(A.AMOUNT,–3), ROUND((TRUNC(A.AMOUNT, –3) +500), –3), COUNT(*)
FROM FEESPAID A,ENROLLMENT B,BATCH C
WHERE A.ROLLNO = B.ROLLNO
AND B.BATCHCODE = C.BATCHCODE
AND C.COURSECODE = 10
GROUP BY TRUNC(A.AMOUNT, –3), ROUND((TRUNC(A.AMOUNT, –3) +500), –3);
