package com.ganesh.ejb3.webservice.credicard;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * CreditCardBeanService service = new CreditCardBeanService();
 * CreditCardBean portType = service.getCreditCardBeanPort();
 * portType.deductAmout(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "CreditCardBeanService", targetNamespace = "http://ejb3.ganesh.com/", wsdlLocation = "http://localhost:9001/Lab8GANESHCreditCard/CreditCardBean?wsdl")
public class CreditCardBeanService extends Service {

	private final static URL CREDITCARDBEANSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.ganesh.ejb3.webservice.credicard.CreditCardBeanService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ganesh.ejb3.webservice.credicard.CreditCardBeanService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:9001/Lab8GANESHCreditCard/CreditCardBean?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:9001/Lab8GANESHCreditCard/CreditCardBean?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		CREDITCARDBEANSERVICE_WSDL_LOCATION = url;
	}

	public CreditCardBeanService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public CreditCardBeanService() {
		super(CREDITCARDBEANSERVICE_WSDL_LOCATION, new QName(
				"http://ejb3.ganesh.com/", "CreditCardBeanService"));
	}

	/**
	 * 
	 * @return returns CreditCardBean
	 */
	@WebEndpoint(name = "CreditCardBeanPort")
	public CreditCardBean getCreditCardBeanPort() {
		return super.getPort(new QName("http://ejb3.ganesh.com/",
				"CreditCardBeanPort"), CreditCardBean.class);
	}

}
