LOAD DATA
INFILE '/MyData/CSV/MumbaiEmployeesFixedLength.txt'
INTO TABLE MumbaiEmployees
(EmployeeNo POSITION(01:10) INTEGER EXTERNAL, 
FirstName POSITION(12:60) CHAR, 
LastName POSITION(62:110) CHAR, 
Salary POSITION(112:121) INTEGER EXTERNAL, 
DeptNo POSITION(123:132) INTEGER EXTERNAL, 
Gender POSITION(134:140) CHAR)