SET TERMOUT OFF
STORE SET STORE REP
SET HEAD OFF
SET PAUSE OFF
SET TERMOUT ON
SELECT 'User: ' || USER || ' on database ' || GLOBAL_NAME, 
	'(TERM=' || USERENV('TERMINAL') || ', AUDSID=' || USERENV('SESSIONID') || ')' AS MYCONTEXT 
	FROM GLOBAL_NAME;

@store
SET TERMOUT ON