package com.ganesh.webservice.account;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * MyAccountService service = new MyAccountService();
 * AccountServiceDelegate portType = service.getAccountServicePort();
 * portType.deposit(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "MyAccountService", targetNamespace = "http://service.bankapp.ganesh.com/", wsdlLocation = "http://localhost:5555/Lab7GANESHBankApp/AccountServicePort?wsdl")
public class MyAccountService extends Service {

	private final static URL MYACCOUNTSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.ganesh.webservice.account.MyAccountService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ganesh.webservice.account.MyAccountService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:5555/Lab7GANESHBankApp/AccountServicePort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:5555/Lab7GANESHBankApp/AccountServicePort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		MYACCOUNTSERVICE_WSDL_LOCATION = url;
	}

	public MyAccountService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public MyAccountService() {
		super(MYACCOUNTSERVICE_WSDL_LOCATION, new QName(
				"http://service.bankapp.ganesh.com/", "MyAccountService"));
	}

	/**
	 * 
	 * @return returns AccountServiceDelegate
	 */
	@WebEndpoint(name = "AccountServicePort")
	public AccountServiceDelegate getAccountServicePort() {
		return super.getPort(new QName("http://service.bankapp.ganesh.com/",
				"AccountServicePort"), AccountServiceDelegate.class);
	}

}
