package com.ganesh.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * HelloService service = new HelloService();
 * HelloDelegate portType = service.getHelloPort();
 * portType.getMessage(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "HelloService", targetNamespace = "http://jaxws.ganesh.com/", wsdlLocation = "http://localhost:5555/Lab1/HelloPort?wsdl")
public class HelloService extends Service {

	private final static URL HELLOSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.ganesh.jaxws.HelloService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ganesh.jaxws.HelloService.class.getResource(".");
			url = new URL(baseUrl, "http://localhost:5555/Lab1/HelloPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:5555/Lab1/HelloPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		HELLOSERVICE_WSDL_LOCATION = url;
	}

	public HelloService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public HelloService() {
		super(HELLOSERVICE_WSDL_LOCATION, new QName("http://jaxws.ganesh.com/",
				"HelloService"));
	}

	/**
	 * 
	 * @return returns HelloDelegate
	 */
	@WebEndpoint(name = "HelloPort")
	public HelloDelegate getHelloPort() {
		return super.getPort(
				new QName("http://jaxws.ganesh.com/", "HelloPort"),
				HelloDelegate.class);
	}

}
