UPDATE DEPOSIT
SET AMOUNT = AMOUNT - 10 WHERE CNAME = 'MADHURI' AND CNAME IN
(SELECT C1.CNAME FROM CUSTOMER C1, CUSTOMER C2 WHERE
C2.CNAME = 'PRAMOD'  AND C1.CITY = C2.CITY);
UPDATE DEPOSIT
SET
AMOUNT = AMOUNT + 10 WHERE CNAME = 'PRAMOD' AND CNAME IN
(SELECT C2.CNAME FROM CUSTOMER C2, CUSTOMER C4 WHERE
C4.CNAME = 'MADHURI' AND C2.CITY = C4.CITY);
