SET TERMOUT OFF ECHO OFF FEED OFF TRIMSPOOL ON HEAD OFF PAGES 0
SPOOL C:/tables.tmp
SELECT 'SELECT COUNT(*), ''' || TABLE_NAME || ''' FROM ' || TABLE_NAME || ';' FROM USER_TABLES;
SPOOL OFF
SET TERMOUT ON
@@C:/tables.tmp
SET HEAD ON FEED ON