#Prerequisites
#=============


#PHASE 1 — Local Package Setup
#=============================
#Step 1: Set your identity in DESCRIPTION
#Open DESCRIPTION and replace the placeholder fields:
usethis::use_gpl3_license() #updating the license

#Step 2: Verify the folder structure
#   DataRecon/
#   ├── DESCRIPTION                        # package metadata
# ├── NAMESPACE                          # exports (auto-generated by roxygen2)
# ├── LICENSE                            # MIT year + copyright holder
# ├── NEWS.md                            # change log
# ├── README.md                          # GitHub landing page
# ├── cran-comments.md                   # notes to CRAN reviewers
# ├── .Rbuildignore                      # files excluded from tarball
# ├── R/
#   │   ├── recon.R                        # main function: recon()
# │   ├── utils.R                        # helper functions
# │   └── rDataRecon-package.R            # package-level documentation
# ├── man/                               # .Rd files — auto-generated, do NOT edit
#   ├── tests/
#   │   ├── testthat.R                     # testthat bootstrap
# │   ├── test_all.R                     # standalone demo/test script
# │   └── testthat/
#   │       └── test-recon.R               # formal unit tests (23 tests)
# ├── vignettes/
#   │   └── introduction.Rmd               # long-form documentation
# └── .github/
#   └── workflows/
#   └── R-CMD-check.yaml           # CI pipeline (Ubuntu/Windows/macOS)

#Step 3: Generate documentation with roxygen2
## Regenerates all man/*.Rd files and NAMESPACE from #' comments
devtools::document()
devtools::check(manual = TRUE) #to see the specific LaTeX error log.
##Do this every time you change any #' roxygen comment.

#Step 4: Run the full test suite
devtools::test()

#Step 5: Build and check the vignette
devtools::build_vignettes()

#Step 6: Run R CMD CHECK locally
devtools::check()# this does entire thing use below
devtools::check(vignettes = FALSE) ## Run this to avoid the Quarto check entirely
devtools::check(document = TRUE) # ##Quick Debug Strategy (fastest) It will point to the exact .Rd issue
devtools::check(cran = TRUE) #additional requirements that CRAN maintainers look

#Step 7: Check against R-devel (CRAN requires this)
devtools::check_win_devel()
devtools::check_win_release()
##An email arrives in ~15 minutes with the results. Must be 0 errors, 0 warnings.

#Step 8: Multi-platform check with rhub
library(rhub)
rhub::rhub_setup()    # first time: authenticate with your email
rhub::rhub_check(platforms = c("linux", "windows", "macos"))
rhub::rhub_doctor()
##Results appear at: https://rhub.r-hub.io/
##https://r-hub.github.io/rhub/index.html

#PHASE 3 — GitHub Setup (Required Before Submission)
#=====================================================
#Step 9: Create GitHub repository
usethis::use_git()
usethis::use_github()   # requires GITHUB_PAT configured
#or
cd path/to/rDataRecon
git init
git add .
git commit -m "Initial CRAN submission: rDataRecon 1.0.0"
git remote add origin https://github.com/ganeshbabunn/rDataRecon.git
git push -u origin main

#Step 10: Update DESCRIPTION with your real GitHub URL
usethis::use_github_links()
##Then re-run
devtools::document()
devtools::check()

#Step 11: Enable GitHub Actions CI
##Automate the Workflow Creation
usethis::use_github_action("check-standard") #only one time, check .github/workflow/R-CHM-Check.yaml is appeared
system("quarto -V") #Check Quarto installation

#CRAN team team checks
#--------------------
rcmdcheck::rcmdcheck(args = "--as-cran", build_args = "--no-build-vignettes")
x <- rcmdcheck::rcmdcheck()
rcmdcheck::check_details(x)

#Filters out the "noise" to show only what's broken
old_check <- rcmdcheck::rcmdcheck("rDataRecon_1.0.0.tar.gz")
new_check <- rcmdcheck::rcmdcheck(".")
rcmdcheck::compare_checks(old_check, new_check)

#Ensures that new code didn't break old functionalit
px <- rcmdcheck::rcmdcheck_process$new()
px
#If you want to be extremely thorough before your first submission, run this:
rcmdcheck::rcmdcheck(args = c("--as-cran", "--no-manual"), error_on = "note")

#PHASE 4 — Final Pre-Submission Checklist
#=========================================
#1. Re-document
devtools::document()
# 2. Full test suite — must be 0 failures
devtools::test()
# 3. Local R CMD CHECK — must be 0 errors, 0 warnings
devtools::check()
# 4. Build the source tarball
devtools::build() # creats ..tar.gz.
# 5.Check the built tarball (most accurate simulation of CRAN check)
rcmdcheck::rcmdcheck()
rcmdcheck::rcmdcheck("../rCoreGage_1.1.0.tar.gz",
                     args     = c("--as-cran"),
                     error_on = "warning")
# 6. Win-builder checks
devtools::check_win_devel()
devtools::check_win_release()
# 7. Spell-check documentation
devtools::spell_check()
# 8. Check URLs are reachable
#install.packages("urlchecker")
urlchecker::url_check()

#PHASE 5 — CRAN Submission
#=========================
#Step 12: Write cran-comments.md
#Check the test enrvo

#Step 13: Submit to CRAN
#=======================
devtools::release() #its depcreated, but good to use
#OR
#use this manually  https://cran.r-project.org/submit.html
usethis::use_release_issue()

#PHASE 7 — Post-Publication
#==========================
#Step 15: Tag the release on GitHub
usethis::use_github_release()

#Step 16: Build a pkgdown documentation website (recommended)
usethis::use_pkgdown_github_pages()  # one-time setup
pkgdown::build_site()                # preview locally
##Your package documentation will be live at: https://YOURGITHUB.github.io/rDataRecon/

#Step 17: Future version updates
sethis::use_version("minor")   # 1.0.0 -> 1.1.0
## or
usethis::use_version("patch")   # 1.0.0 -> 1.0.1
## Update NEWS.md, re-run full check cycle, then:
devtools::release()


#Other
#======
#forcing to install package from github
remotes::install_github("ganeshbabunn/rCoreGage") #install from remote
packageVersion("rCoreGage") #verifying the package version
remotes::install_github("ganeshbabunn/rCoreGage", force = TRUE) #force it

# Run the Below if you want to run locally
devtools::load_all()
devtools::load_all("C:\\Kriyababa\\GitHub\\rCoreGage\\inst\\STUDY01_TRAIL01/") #modify the path accordingly


#Use this during development:
if (!requireNamespace("rCoreGage", quietly = TRUE)) {
  devtools::load_all("../rCoreGage")  # adjust path
} else {
  devtools::load_all("../rCoreGage")
}


install.packages("C:/Kriyababa/GitHub/rCoreGage_0.1.0.tar.gz", repos = NULL, type = "source")

#adding the files to .RBuildIgnore File.
usethis::use_build_ignore("cran-comments.md")
usethis::use_build_ignore("LICENSE.md")
usethis::use_build_ignore("inst/STUDY01_TRAIL01/")

#license in CRAN
#https://cran.r-project.org/web/licenses/

# Add missing dependencies
usethis::use_package("tidyverse", type = "Suggests")
usethis::use_package("remotes", type = "Suggests")

update.packages(ask = FALSE, checkBuilt = TRUE)
install.packages(c("sessioninfo", "devtools", "quarto"))

#choose license
#https://github.com/github/choosealicense.com
#https://r-hub.github.io/rhub/index.html # rhub

#Cran repositiory View
#https://cran.r-project.org/web/packages/
