package com.ganesh.webservice.creditcard;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "CreditCardServiceDelegate", targetNamespace = "http://service.creditcard.ganesh.com/")
public interface CreditCardServiceDelegate {

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "deductAmount", targetNamespace = "http://service.creditcard.ganesh.com/", className = "com.ganesh.webservice.creditcard.DeductAmount")
	@ResponseWrapper(localName = "deductAmountResponse", targetNamespace = "http://service.creditcard.ganesh.com/", className = "com.ganesh.webservice.creditcard.DeductAmountResponse")
	public void deductAmount(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") double arg1);

}
