package com.ganesh.webservice.creditcard;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * MyCreditCardService service = new MyCreditCardService();
 * CreditCardServiceDelegate portType = service.getCreditCardServicePort();
 * portType.deductAmount(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "MyCreditCardService", targetNamespace = "http://service.creditcard.ganesh.com/", wsdlLocation = "http://localhost:5555/Lab7GANESHCreditCardApp/CreditCardServicePort?wsdl")
public class MyCreditCardService extends Service {

	private final static URL MYCREDITCARDSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.ganesh.webservice.creditcard.MyCreditCardService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ganesh.webservice.creditcard.MyCreditCardService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:5555/Lab7GANESHCreditCardApp/CreditCardServicePort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:5555/Lab7GANESHCreditCardApp/CreditCardServicePort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		MYCREDITCARDSERVICE_WSDL_LOCATION = url;
	}

	public MyCreditCardService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public MyCreditCardService() {
		super(MYCREDITCARDSERVICE_WSDL_LOCATION, new QName(
				"http://service.creditcard.ganesh.com/", "MyCreditCardService"));
	}

	/**
	 * 
	 * @return returns CreditCardServiceDelegate
	 */
	@WebEndpoint(name = "CreditCardServicePort")
	public CreditCardServiceDelegate getCreditCardServicePort() {
		return super.getPort(new QName("http://service.creditcard.ganesh.com/",
				"CreditCardServicePort"), CreditCardServiceDelegate.class);
	}

}
