package com.ganesh.jaxws.account;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * AccountBeanService service = new AccountBeanService();
 * AccountBean portType = service.getAccountBeanPort();
 * portType.deposit(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "AccountBeanService", targetNamespace = "http://account.ejb3.ganesh.com/", wsdlLocation = "http://127.0.0.1:9001/Lab6/AccountBean?wsdl")
public class AccountBeanService extends Service {

	private final static URL ACCOUNTBEANSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.ganesh.jaxws.account.AccountBeanService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ganesh.jaxws.account.AccountBeanService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://127.0.0.1:9001/Lab6/AccountBean?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:9001/Lab6/AccountBean?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		ACCOUNTBEANSERVICE_WSDL_LOCATION = url;
	}

	public AccountBeanService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public AccountBeanService() {
		super(ACCOUNTBEANSERVICE_WSDL_LOCATION, new QName(
				"http://account.ejb3.ganesh.com/", "AccountBeanService"));
	}

	/**
	 * 
	 * @return returns AccountBean
	 */
	@WebEndpoint(name = "AccountBeanPort")
	public AccountBean getAccountBeanPort() {
		return super.getPort(new QName("http://account.ejb3.ganesh.com/",
				"AccountBeanPort"), AccountBean.class);
	}

}
